services:
  frontend:
    build: .
    container_name: shorty_url_frontend
    ports:
      - "${PORT}:5173"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - https_network
    restart: unless-stopped

networks:
  https_network:
    name: ${HTTPS_NETWORK}
    external: true
