services:
  frontend:
    build: .
    ports:
      - "${PORT}:5173"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - https_network

networks:
  https_network:
    name: ${HTTPS_NETWORK}
    external: true
